# Generated by Django 4.2.3 on 2024-01-08 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diabetes_disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('height', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('waist', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('weight', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('gender', models.BooleanField()),
                ('druge_history', models.BooleanField()),
                ('vegetabls', models.BooleanField()),
                ('His_family_glucose', models.BooleanField()),
            ],
        ),
    ]
