# Generated by Django 4.2.3 on 2024-01-08 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ckd_disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('gender', models.BooleanField()),
                ('anemia', models.BooleanField()),
                ('druge_history', models.BooleanField()),
                ('His_cvd', models.BooleanField()),
                ('hypertention', models.BooleanField()),
                ('proteinuria', models.BooleanField()),
                ('vascular_disease', models.BooleanField()),
                ('diabetes_mellitus', models.BooleanField()),
                ('His_CHF', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='cvd_disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('gender', models.BooleanField()),
                ('sbp_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('smoke', models.BooleanField()),
                ('diabetes', models.BooleanField()),
                ('waist', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('hip', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
            ],
        ),
        migrations.CreateModel(
            name='stroke_disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('sbp_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('gender', models.BooleanField()),
                ('related_medicine', models.BooleanField()),
                ('diabetes', models.BooleanField()),
                ('smoke', models.BooleanField()),
                ('CVD_disease', models.BooleanField()),
                ('AF_disease', models.BooleanField()),
                ('LVH_disease', models.BooleanField()),
            ],
        ),
    ]
