# Generated by Django 4.2.3 on 2024-05-21 05:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digweb', '0002_ckd_disease_cvd_disease_stroke_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='alzheimer_disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('height', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('weight', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('SBP', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('Education', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9)])),
                ('gender', models.BooleanField()),
                ('Cholesterol', models.BooleanField()),
                ('Activity', models.BooleanField()),
            ],
        ),
    ]
